%Cargar y guardar en .mat
[filename, pathname] = uigetfile( ...
{ %%'*.mat','MAT-files (*.mat)'; ...
   %%'*.slx;*.mdl','Models (*.slx, *.mdl)'; ...
   '*.*',  'All Files (*.*)'}, ...
  'Seleccione las slides a analizar', ...
   'MultiSelect', 'on');
addpath(pathname);

Todas_rx = {};
for i=1:size(filename,2)
    rx.im = dicomread(filename{1,i});
    rx.info = dicominfo(filename{1,1});
    Todas_rx{i,1} = rx;    
end
